command-node:

    - aaa:
          description:
    
  - access-list:
      
  - affinity-map:
  - alias:
  - appletalk:
  - arp:
  - atm:
  - banner:
  - bluetooth:
  - class-map:
  - clns:
  - crypto:
  - dns:
  - do:
  - docsis:
  - dot1x:
  - dsa:
  - dsl:
  - eap:
  - enable:
  - end:
  - ethernet:
  - exit:
  - feature:
  - fiberchannel:
  - filter:
  - hdlc:
  - hostname:
  - ieee-spb:
  - infiniband:
  - interface:
  - ipv4:
  - ipv6:
  - key-chain:
  - l2tp:
  - line:
  - link-aggregation-group:
  - lldp:
  - mac-address-table:
  - macsec:
  - mdns:
  - mpls:
  - multicast-vpn:
  - netflow:
  - nfc:
  - ntp:
  - omnipath:
  - openvswitch:
  - policy:
  - policy-map:
  - ppp:
  - ptp:
  - qos:
  - quic:
  - rlogin:
  - router:
  - segment-routing:
  - slip:
  - snmp:
  - spanning-tree:
  - ssh:
  - system:
  - tcp:
  - telnet:
  - trill:
  - udp:
  - username:
  - vlan:
  - vnc:
  - vrf:
  - x25:
